version: '3.7'
services:
    mongo:
        build: ./docker-mongodb/
        networks:
            - api-net
        logging:
            options:
                max-size: 10m
                max-file: "3"

    api:
        build: ./APIMongoDB/
        depends_on:
            - mongo
        networks:
            - api-net
        ports:
            - "5000:5000"

  
networks:
    api-net:
        external: true